apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: app4-workload
  namespace: development
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: app4-workload
    apps.tanzu.vmware.com/has-tests: "true"
    app: app4-workload
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/ignaciylipm/app4-workload.git
      ref:
        branch: main
